name = "s7ae-stats-worker"
type = "javascript"
account_id = "YOUR_CF_ACCOUNT_ID"
workers_dev = true
route = "s7ae.net/api/*"
zone_id = "YOUR_ZONE_ID"

kv_namespaces = [
  { binding = "ACCESS_LOGS", id = "YOUR_KV_NAMESPACE_ID", preview_id = "YOUR_KV_NAMESPACE_ID" }
]
